### ISSUE TITLE
Buildpack does not yet support heroku-16 stack

### ISSUE THREAD

**Issue by bsionixxtech** [mojodna/heroku-buildpack-cairo#16]
Building source:
remote: 
remote: -----> Cairo app detected
remote: -----> Vendoring binaries
remote:        Fetching https://s3.amazonaws.com/mojodna-heroku/heroku-16/cairo-1.14.6-1.tar.gz
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote:  !     Push rejected, failed to compile Cairo app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....

**Comment by sethfitz** [comment]
This buildpack doesn't yet support the `heroku-16` stack.

**Comment by bsionixxtech** [comment]
THanks for the info.
My app heroku Stack is cedar-14. Do you have any idea how it is searching for heroku-16?

**Comment by frazras** [comment]
@bsionixxtech just set your stack back to cedar-14, heroku-16 is now the default: Use this command
`heroku stack:set cedar-14`

**Comment by partlyhuman** [comment]
cedar-14 has been sunset and you can no longer select it. 

```
$ heroku stack:set cedar-14
 !    This version of the API has been Sunset.
 !    Please see https://devcenter.heroku.com/changelog-items/1147 for more information.

**Comment by xavriley** [comment]
The `cedar-14` stack is still available and will be supported through to April 2019 https://devcenter.heroku.com/articles/stack

@partlyhuman That error you were receiving above was likely to be a result of using an older version of the `heroku` command line tools.

**Comment by enzogain** [comment]
Hi, 
Any informations about the release date of this buildpack for heroku-16 ? :D

**Comment by olivierlesnicki** [comment]
+1

**Comment by y-ich** [comment]
+1

**Comment by tigercosmos** [comment]
+1

**Comment by ShayBox** [comment]
+1

**Comment by marcsyp** [comment]
+1 for heroku-16.  

I actually have a project that depends heavily on text2png and I have been running on a local server with no problems.  My heroku instance is borked, however.  Tried downgrading to cedar-14, no luck.  I've tried every piecemeal solution I can find going all the way back to comments + repos from 2011, with no luck.  It seems the elspoono repo is gone, as well.  

Does anyone have any intention of getting this back up and running?  It's beyond my skill level, so I have to rely on the generous community.  But given that I am trying to launch my product in 3 weeks, it looks like I may have to ditch heroku and look into hosting a Windows machine on Azure, unless anyone has any suggestions....

**Comment by wellcaffeinated** [comment]
+1

**Comment by JordanAdams** [comment]
We've forked this to https://github.com/sky-uk/heroku-buildpack-cairo where we migrated the dependencies on S3 adding support for the following stacks:

- Cedar 14
- Heroku 16
- Heroku 18

**Comment by OKNoah** [comment]
I believe this also happens with herokuish

**Comment by yanngv29** [comment]
i'm using https://github.com/sky-uk/heroku-buildpack-cairo  with Heroku-16.

When switching to Heroku 18, i got an error at runtime : 

```
 catch exception !!! Error: libpng12.so.0: cannot open shared object file: No such file or directory
2018-09-18T14:49:07.645053+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:682:18)
2018-09-18T14:49:07.645055+00:00 app[web.1]:     at Module.load (module.js:566:32)
2018-09-18T14:49:07.645057+00:00 app[web.1]:     at tryModuleLoad (module.js:506:12)
2018-09-18T14:49:07.645058+00:00 app[web.1]:     at Function.Module._load (module.js:498:3)
2018-09-18T14:49:07.645059+00:00 app[web.1]:     at Module.require (module.js:597:17)
2018-09-18T14:49:07.645061+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-09-18T14:49:07.645062+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/canvas/lib/bindings.js:3:18)
2018-09-18T14:49:07.645064+00:00 app[web.1]:     at Module._compile (module.js:653:30)
2018-09-18T14:49:07.645065+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:664:10)
2018-09-18T14:49:07.645066+00:00 app[web.1]:     at Module.load (module.js:566:32)
2018-09-18T14:49:07.645068+00:00 app[web.1]:     at tryModuleLoad (module.js:506:12)
2018-09-18T14:49:07.645069+00:00 app[web.1]:     at Function.Module._load (module.js:498:3)
2018-09-18T14:49:07.645070+00:00 app[web.1]:     at Module.require (module.js:597:17)
2018-09-18T14:49:07.645072+00:00 app[web.1]:     at require (internal/module.js:11:18)
2018-09-18T14:49:07.645074+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/canvas/lib/canvas.js:13:14)
2018-09-18T14:49:07.645075+00:00 app[web.1]:     at Module._compile (module.js:653:30)
```
any idea ?

**Comment by benpdavison** [comment]
Just thought I would leave a comment with how I resolved this for myself on heroku-18.

I was receiving errors such as this when upgrading the stack:

```

 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.7/runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "/app/.heroku/python/lib/python3.7/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/app/server.py", line 40, in <module>
     from render_handler import RenderHandler
   File "/app/handlers/render_handler.py", line 6, in <module>
     import cairosvg
   File "/app/.heroku/python/lib/python3.7/site-packages/cairosvg/__init__.py", line 42, in <module>
     from . import surface  # noqa isort:skip
   File "/app/.heroku/python/lib/python3.7/site-packages/cairosvg/surface.py", line 25, in <module>
     import cairocffi as cairo
   File "/app/.heroku/python/lib/python3.7/site-packages/cairocffi/__init__.py", line 50, in <module>
     ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
   File "/app/.heroku/python/lib/python3.7/site-packages/cairocffi/__init__.py", line 45, in dlopen
     raise OSError(error_message)  # pragma: no cover
 OSError: no library called "libcairo-2" was found
 cannot load library 'libcairo.so.2': libpng12.so.0: cannot open shared object file: No such file or directory
 cannot load library 'libcairo.so': libcairo.so: cannot open shared object file: No such file or directory
 cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory
 cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory
```

After a lot of hours of researching I finally decided to try and install the dependencies with `apk` as heroku-18 is based upon Ubuntu 18.04.

So what I did was:
Delete this buildpack from my buildpacks
Add the [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt)
Add the Aptfile to the root directory of the code with the following packages
```
libc6
libcairo2
python-cairo
```
Redeploy


From then on everything worked
